### ISSUE TITLE
/docs/tasks/federation/administer-federation/events.md

### ISSUE THREAD

**Issue by markthink** [k8smeetup/website-tasks#2272]
Source File: [/docs/tasks/federation/administer-federation/events.md](https://github.com/kubernetes/website/blob/release-1.14/content/en/docs/tasks/federation/administer-federation/events.md)

**Comment by markthink** [comment]
Thank you @xichengliudui, this issue had been assigned to you.

**Comment by xichengliudui** [comment]
pushed

**Comment by markthink** [comment]
Sorry @xichengliudui, only issues with special values ('pushed') can be accepted.
