### ISSUE TITLE
/docs/tasks/federation/administer-federation/secret.md

### ISSUE THREAD

**Issue by markthink** [k8smeetup/website-tasks#2278]
Source File: [/docs/tasks/federation/administer-federation/secret.md](https://github.com/kubernetes/website/blob/release-1.14/content/en/docs/tasks/federation/administer-federation/secret.md)

**Comment by markthink** [comment]
Thank you @MJ-CJM, this issue had been assigned to you.

**Comment by MJ-CJM** [comment]
@markthink 小龙哥，这篇文章已经翻译过了。release-1.14里面已经有了，是需要修改，还是重新翻译下。
