### ISSUE TITLE
/docs/setup/windows/intro-windows-in-kubernetes.md

### ISSUE THREAD

**Issue by markthink** [k8smeetup/website-tasks#2403]
Source File: [/docs/setup/windows/intro-windows-in-kubernetes.md](https://github.com/kubernetes/website/blob/release-1.14/content/en/docs/setup/windows/intro-windows-in-kubernetes.md)

**Comment by markthink** [comment]
Thank you @ten2ton, this issue had been assigned to you.

**Comment by TongHan0389** [comment]
There is no source file.
