### ISSUE TITLE
/docs/tasks/federation/administer-federation/hpa.md

### ISSUE THREAD

**Issue by markthink** [k8smeetup/website-tasks#3070]
Source File: [/docs/tasks/federation/administer-federation/hpa.md](https://github.com/kubernetes/website/blob/release-1.16/content/en/docs/tasks/federation/administer-federation/hpa.md)

**Comment by 3ks** [comment]
@markthink [source file](https://github.com/kubernetes/website/blob/release-1.16/content/en/docs/tasks/federation/administer-federation/hpa.md) 在 [master-en](https://github.com/kubernetes/website/blob/master/content/en/docs/tasks/federation/administer-federation/hpa.md) 中已经不存在，目前整个 [master-en-doc](https://github.com/kubernetes/website/tree/master/content/en/docs) 似乎都没有 `Federated Ingress` 相关的内容，不知道是否需要继续翻译。

**Comment by markthink** [comment]
Thank you @Sophy417, this issue had been assigned to you.
