### ISSUE TITLE
/docs/concepts/workloads/controllers/garbage-collection.md

### ISSUE THREAD

**Issue by markthink** [k8smeetup/website-tasks#3505]
Source File: [/docs/concepts/workloads/controllers/garbage-collection.md](https://github.com/kubernetes/website/blob/release-1.16/content/en/docs/concepts/workloads/controllers/garbage-collection.md)

Diff 查看原始文档更新差异命令:
 ```bash
git diff release-1.14 release-1.16 -- content/en/docs/concepts/workloads/controllers/garbage-collection.md
```

**Comment by TongHan0389** [comment]
This task has been translated.

**Comment by markthink** [comment]
Thank you @lpf7551321, this issue had been assigned to you.
