### ISSUE TITLE
/docs/tasks/administer-cluster/out-of-resource.md

### ISSUE THREAD

**Issue by markthink** [k8smeetup/website-tasks#3614]
Source File: [/docs/tasks/administer-cluster/out-of-resource.md](https://github.com/kubernetes/website/blob/release-1.16/content/en/docs/tasks/administer-cluster/out-of-resource.md)

Diff 查看原始文档更新差异命令:
 ```bash
git diff release-1.14 release-1.16 -- content/en/docs/tasks/administer-cluster/out-of-resource.md
```

**Comment by markthink** [comment]
Thank you @lpf7551321, this issue had been assigned to you.

**Comment by lpf7551321** [comment]
/ merged
