### ISSUE TITLE
/docs/tasks/configure-pod-container/quality-service-pod.md

### ISSUE THREAD

**Issue by markthink** [k8smeetup/website-tasks#3622]
Source File: [/docs/tasks/configure-pod-container/quality-service-pod.md](https://github.com/kubernetes/website/blob/release-1.16/content/en/docs/tasks/configure-pod-container/quality-service-pod.md)

Diff 查看原始文档更新差异命令:
 ```bash
git diff release-1.14 release-1.16 -- content/en/docs/tasks/configure-pod-container/quality-service-pod.md
```

**Comment by xichengliudui** [comment]
pushed
