### ISSUE TITLE
/docs/concepts/workloads/_index.md

### ISSUE THREAD

**Issue by fleeto** [k8smeetup/website-tasks#934]
Path：`/docs/concepts/workloads/_index.md`

[Source code](https://github.com/kubernetes/website/tree/release-1.12/content/en//docs/concepts/workloads/_index.md)

**Comment by chenrui333** [comment]
已经翻译过了。
https://github.com/kubernetes/website/blob/release-1.12/content/zh/docs/concepts/workloads/_index.md
