### ISSUE TITLE
/docs/tasks/configure-pod-container/configure-volume-storage.md

### ISSUE THREAD

**Issue by fleeto** [k8smeetup/website-tasks#953]
Path：`/docs/tasks/configure-pod-container/configure-volume-storage.md`

[Source code](https://github.com/kubernetes/website/tree/release-1.12/content/en//docs/tasks/configure-pod-container/configure-volume-storage.md)

**Comment by chenrui333** [comment]
PR, https://github.com/kubernetes/website/pull/11460

**Comment by MJ-CJM** [comment]
PR, kubernetes/website#11602
