### ISSUE TITLE
/docs/concepts/overview/_index.md

### ISSUE THREAD

**Issue by fleeto** [k8smeetup/website-tasks#957]
Path：`/docs/concepts/overview/_index.md`

[Source code](https://github.com/kubernetes/website/tree/release-1.12/content/en//docs/concepts/overview/_index.md)

**Comment by chenrui333** [comment]
这个文件已经存在，https://github.com/kubernetes/website/blob/release-1.12/content/zh/docs/concepts/overview/_index.md

**Comment by chenrui333** [comment]
但是有点格式问题。我下面才是比较正确的格式。
https://github.com/chenrui333/website/blob/zh-trans-setup-independent-index/content/zh/docs/setup/independent/_index.md
